# This is a basic workflow to help you get started with Actions

name: Simple

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ github-workflow ]
  pull_request:
    branches: [ github-workflow ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  # Runs a smoke test to filter out uncompilable pushes and merges
  smoke-test:

    runs-on: ubuntu-latest
    container: saw235/riscsv

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Output verilator version
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.